### ISSUE TITLE
Post Data not sent

### ISSUE THREAD

**Issue by dlorenso** [RxPHP/RxHttp#3]
This sample code is not working.  The post data is not sent to my web server:
```
$postData = json_encode(["test" => "data"]);
$headers  = ['Content-Type' => 'application/json'];

$source = \Rx\React\Http::post('https://www.example.com/', $postData, $headers);

$source->subscribe(
    function ($data) {
        echo $data, PHP_EOL;
    },
    function (\Exception $e) {
        echo $e->getMessage(), PHP_EOL;
    },
    function () {
        echo "completed", PHP_EOL;
    }
);
```

I am reading the post data on the server side like this:

```
        // read json post data
        $data = json_decode(file_get_contents('php://input'), true);
```

I know I am reading the data properly because this works on the command line:

```
curl -H "Content-Type: application/json" -d '{"test":"data"}' https://www.example.com/
```

**Comment by dlorenso** [comment]
Ok, your library is fine.  It's the example that needs help.

I fixed the problem by adding the content-length to the http headers.  I think Apache/PHP that I'm using requires this header or the JSON data will not present in php://input

`$headers = ['Content-Type' => 'application/json', 'Content-Length' => strlen($postData)];
`

Perhaps when doing a post and post data is present you should automatically add this header for the user?  I can get it working fine by adding it myself, but I think this is something the class can handle on users behalf, yes?

**Comment by CedX** [comment]
I've encountered the same issue. It seems that the `Content-Length` header is required most of the times.
See: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4

> For compatibility with HTTP/1.0 applications, HTTP/1.1 requests containing a message-body MUST include a valid Content-Length header field unless the server is known to be HTTP/1.1 compliant. If a request contains a message-body and a Content-Length is not given, the server SHOULD respond with 400 (bad request) if it cannot determine the length of the message, or with 411 (length required) if it wishes to insist on receiving a valid Content-Length.

+1 for adding the `Content-Length` header automatically if it is not already set (and if its value can be computed from the request body).

**Comment by davidwdan** [comment]
Anyone want to make a PR?
